[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "^3.10"
seaborn = "^0.13.2"
jupyter = "^1.0.0"
scikit-learn = "^1.4.1.post1"
opendatasets = "^0.1.22"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
